### PR TITLE
Fix footer

### LINKED ISSUE #82: remove the "follow us" section from the footer

### PR DESCRIPTION
**Pull request by JanaKhanji**
by tommy

### CODE REVIEW

**Review by osamaakb — CHANGES_REQUESTED** [review]
Take another look there are problems in these files

File: src/Components/CollectionCard/CollectionCardModal.js [hunk 1]
```diff
@@ -75,3 +157,4 @@ export default function CollectionCardModal({ card, setShowModal }) {
     </div>
   );
 }
+>>>>>>> 4e525798c2f5cc99f96c5cfb2c290846f7aef3f8
```
Comment (osamaakb) [inline src/Components/CollectionCard/CollectionCardModal.js]: please fix these

File: src/Components/CollectionCard/CollectionCardModal.js [hunk 2]
```diff
@@ -8,6 +8,88 @@ import Img from '../../assets/icons/image 22.png';
 import collection from '../../Constants/collection.js';
 
 export default function CollectionCardModal({ card, setShowModal }) {
+<<<<<<< HEAD
```
Comment (osamaakb) [inline src/Components/CollectionCard/CollectionCardModal.js]: same here

**Review by osamaakb — CHANGES_REQUESTED** [review]

**Comment by osamaakb** [comment]
@Tommymaxprog @JanaKhanji I fixed the conflicts and errors, does it look good?

**Review by osamaakb — APPROVED** [review]
